---
- name: Including distro-specific variables
  include_vars: "vars_{{ ansible_distribution }}.yml"
  
- name: "Setting things up for {{ ansible_distribution }}"
  include_tasks: "setup_{{ ansible_distribution }}.yml"
  when: ansible_distribution in [ 'Ubuntu' ]
