---
- name: "Ensuring ppa:remmina-ppa-team/remmina-next is used"
  apt_repository: repo='ppa:remmina-ppa-team/remmina-next'

- name: Installing packages
  apt:
    name: "{{ mage_packages }}"
    state: latest
    update_cache: true

