---
- name: "Ensuring {{ item }} PPA is used"
  apt_repository: repo="{{ item }}"
  with_items:
    - ppa:phoerious/keepassxc
    - ppa:remmina-ppa-team/remmina-next
    - ppa:alexx2000/doublecmd
    - ppa:eivnaes/network-manager-sstp

- name: Installing packages
  apt:
    name: "{{ mage_packages }}"
    state: latest
    update_cache: true

