---

- name: Ensure apt keys are configured
  apt_key:
    url: "{{ item.keyurl | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    id: "{{ item.keyid | default(omit) }}"
    state: present
  when: item.keyurl is defined or item.keyid is defined
  with_items: "{{ apt_repos }}"

- name: Ensure PPAs are configured
  apt_repository: repo="{{ item.repo }}" codename="{{ item.codename | default(omit)}}"
  loop: "{{ apt_repos }}"
  when: apt_repos | selectattr("repo", "defined") | list | length > 0

- name: Ensure packages are installed
  apt:
    name: "{{ mage_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Ensure snaps are installed
  snap:
    name: "{{ mage_snaps }}"

- name: Ensure remmina services are connected
  shell: |
    snap connect remmina:avahi-observe :avahi-observe
    snap connect remmina:cups-control :cups-control
    snap connect remmina:mount-observe :mount-observe
    snap connect remmina:password-manager-service :password-manager-service